version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - uname -r
      - sudo service docker start
      - echo Logging in to Amazon ECR...
      - aws --region us-west-2 ecr get-login-password | docker login --username AWS --password-stdin 011974343726.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Building nginx image...
      - sudo /usr/local/bin/docker build -t nginx .
      - sudo /usr/local/bin/docker tag nginx:latest 011974343726.dkr.ecr.us-west-2.amazonaws.com/nginx:newest
  post_build:
    commands:
      - echo Pushing nginx image to Amazon ECR...
      - docker push 011974343726.dkr.ecr.us-west-2.amazonaws.com/nginx:newest
      - echo Deploying nginx Docker image to AWS CodeDeploy...
      #- aws deploy create-deployment --application-name MyApp --deployment-group-name MyDeploymentGroup --revision revisionType=AppSpecContent,content="{\"ImageUri\": \"011974343726.dkr.ecr.us-west-2.amazonaws.com/my-nginx:newest\"}"

artifacts:
  files:
    - "**/*"
